# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Canterbury Voice Release
tagline: Equipment Competitors Demand
email: bruce@cvr.co.nz
description: > # this means to ignore newlines until "baseurl:"
  The World's most reliable voice activated clay target release system for Trap/DTL, Skeet, 5-Stand & ZZ/Helice shooting. No more complaints about pullers and no more 'turning down' fast or slow targets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cvr.co.nz" # the base hostname & protocol for your site
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      
# Build settings
markdown: kramdown

gems:
 - jekyll-sitemap
